### ISSUE TITLE
Problem playing twitch favorites

### ISSUE THREAD

**Issue by falcom4ever** [charnet3d/DesktopLiveStreamer#3] opened 2013-06-29 17:31 UTC
Hello,

I have a problem with the favorites stream list part in the application. It works fine with the other options, but not with favorites.

If I enter a favorite stream channel called thetopcut. It says it is online, but when I click on open nothing happens (VLC does not opens the stream).

Any idea why it does not work with this channel ?
![screen](https://f.cloud.github.com/assets/4884762/726245/991119d6-e0e1-11e2-935c-5d9aa4a9837e.jpg)

Here is how I entered my channel :
![screen2](https://f.cloud.github.com/assets/4884762/726246/b668e89c-e0e1-11e2-918e-45f188ba88de.jpg)

Thanks in advance for your help !

**Comment by oldage** [comment] 2013-08-16 21:13
I'm having this issue too, none of my favourites are working.

**Comment by charnet3d** [comment] 2013-08-19 23:45
Hi there friends, Sorry for the huge delay on my answers :c I've got quite a lot happening in my life (graduation, moving to another city for work, new computer ....). So I'm finally checking my code to fix all the bugs I have had reported to me, for this one I have found a small bug where if you have a favorite URL ending with a / (slash) it would make my code for parsing the channel name not work and thus give wrong reports as to which channels are ON and which are OFF.

So here in my case I had a channel which was offline but was reported as online, it had a trailing / in the URL. For your case falcom4ever I don't really know what's wrong with it. As it worked as intended for me when i didn't have a / at the end.

What about you oldage, can you tell me which URL(s) did you try to play ? Also check the channel in your browser to see if it's offline before playing, with this you can be sure that it's the ON/OFF checking that's wrong and not the playing feature.

And thanks a lot btw, really nice of you to take some time to report some bugs :)

**Comment by gammmae105** [comment] 2013-08-22 05:39
Hey Charaf, the program isn't working for me at all since 2 weeks ago. :( Clicking play does nothing but give me error saying the program stopped working, I've tried reinstalling older versions and the updated one too, but still not working.

**Comment by oldage** [comment] 2013-08-22 17:11
The URLs I tried to play are 

http://www.twitch.tv/draskyll
http://www.twitch.tv/lirik
http://www.twitch.tv/sing_sing

Of course I looked on twitch to see if they were online. As I'm typing this Lirik is streaming and I am unable to watch him with DLS.

I am also unable to select a quality from the 'currently online' list even if they're online, and when I click play after selecting a streamer not on my favourites I get 'Desktop Livestreamer has stopped working'.

This is the signature if you're anything with it. (It's Dutch but I think you know what to look for?)
  Gebeurtenisnaam van probleem: CLR20r3
  Probleemhandtekening 01:  desktoplivestreamer.exe
  Probleemhandtekening 02:  0.9.2.0
  Probleemhandtekening 03:  5116da0e
  Probleemhandtekening 04:  DesktopLiveStreamer
  Probleemhandtekening 05:  0.9.2.0
  Probleemhandtekening 06:  5116da0e
  Probleemhandtekening 07:  1e
  Probleemhandtekening 08:  e3
  Probleemhandtekening 09:  System.NullReferenceException
  Versie van besturingssysteem: 6.1.7601.2.1.0.256.1
  Landinstelling-id:    2067
  Aanvullende informatie 1: 0a9e
  Aanvullende informatie 2: 0a9e372d3b4ad19135b953a78882e789
  Aanvullende informatie 3: 0a9e
  Aanvullende informatie 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by charnet3d** [comment] 2013-08-25 21:07
Just released version 0.9.3 to fix the qualities issue, I tried the mentioned streams in this new version, and they worked fine for me. Maybe the bug that you were suffering from was related to the outdated version of livestreamer... Check out the read me file for the latest version and tell me if everything is fixed for you :)
![1](https://f.cloud.github.com/assets/2863796/1023085/36f27e8c-0dca-11e3-849b-53bbe166ba35.png)

**Comment by oldage** [comment] 2013-08-26 09:54
That did it for the most part. However I've tried about 7 different streams and I've gotten 'VLC could not find fd://0' twice, not sure if that's an issue you know of (can't open the readme so I don't know if it's mentioned there). Oh and I'm sure you've already been notified of this but will this have any impact? http://blog.twitch.tv/2013/08/major-changes-coming-to-twitch-transcodes/

Either way, thank you for your work, my favourites are working now. :)

**Closed as completed** 2013-12-21 19:17 UTC
